### ISSUE TITLE
What it is?

### ISSUE THREAD

**Issue by Archakov06** [aziev/codepaper#1]
Hello, @aziev! Thank you for this particles. But i don't know how use it. It is ready to build?

**Comment by aziev** [comment]
Hi, @Archakov06!
We just started to develop our open-source website with @teslaAi. We want to publish there translated articles related to IT.

**Comment by Archakov06** [comment]
@aziev ooohh, very nice! It's good ideas. @teslaAi otlichno umet translate articles! It's my english teacher. You see my super good english? Yes! My english is beautifully! Can i see design of this project? Or you only make structure?

**Comment by aziev** [comment]
@Archakov06 Design is on development mode too :)

**Comment by timurziev** [comment]
Archakov06 was that sarcasm or what? Actually I haven't taught you anything)

**Comment by Archakov06** [comment]
@teslaAi no, it's not sarcasm) I look the video on Ororo for your advice)
